### ISSUE TITLE
Row Content is NOT properly wrapped to corresponding cells in last rows (on few pages) and cutoff on next page

### ISSUE THREAD

**Issue by jackiewang5566** [simonbengtsson/jsPDF-AutoTable#469]
When displaying long content in the last row of page which will expand to next page and the cell content on the next page will be cutoff. I'm using overflow: linebreak with columnWidth: 'auto' as the long example did. I've created a stackblitz to reproduce this issue and a screenshot, any help would be much appreciated.

https://stackblitz.com/edit/angular-cq93fv

<img width="655" alt="Screen Shot 2019-03-18 at 10 36 39 PM" src="https://user-images.githubusercontent.com/13965345/54576442-8bdb3380-49ce-11e9-93c6-7722dd7cf80b.png">

**Comment by jackiewang5566** [comment]
Any update for this issue?

**Comment by simonbengtsson** [comment]
No one has started work on this yet as far as I know

**Comment by principalX** [comment]
After upgrading everything, ran into this issue today as well.

**Comment by principalX** [comment]
researching it.. looks like the issue started back in version 3.0.10

**Comment by rong4188** [comment]
it seems to be a bug in printFullRow method. It calculates remainHeight like this rCellHeight = cell.height - remainingPageSpace. but remainingPageSpace is usually more than the printed text height. the correct calculation should be rCellHeight = cell.height - printedLinesOccupiedSpace

**Comment by simonbengtsson** [comment]
@jackiewang5566 is the merged pull request from @rong4188 fixing the issue for you?

**Comment by jackiewang5566** [comment]
I pulled latest version 3.1.1 which included the the merge from @rong4188 , but still seeing the issue.
![image](https://user-images.githubusercontent.com/13965345/55812794-9ebac280-5ab9-11e9-9576-0cd01423900d.png)

**Comment by simonbengtsson** [comment]
You need to use master and not 3.1.1 I think. I want to verify this is fixed before releasing a new version.

**Comment by jackiewang5566** [comment]
I updated my package.json using master branch "jspdf-autotable": "simonbengtsson/jsPDF-AutoTable#master", it included the latest commit from @rong4188 , but still seeing the cutoff issue,
screenshot below.
![image](https://user-images.githubusercontent.com/13965345/55814728-19d1a800-5abd-11e9-99dd-75fa884ed3df.png)

**Comment by simonbengtsson** [comment]
Seems to still be an issue then so I'll leave the issue open. Help wanted!

**Comment by rong4188** [comment]
well, interesting.  Below is what I have got in your case in this link: https://stackblitz.com/edit/angular-cq93fv . I just tried replacing the piece of code with my code in chrome dev tool and it looked ok. it must be some other details that I didn't realize. can you update your link code to the latest version so that I can look further?
![image](https://user-images.githubusercontent.com/10201833/55842428-a9dc2400-5b87-11e9-8f78-f1a6f3d27c44.png)

**Comment by jackiewang5566** [comment]
I tried to update the package to master branch on Stackblitz, but it seems that Stackblitz have some issues loading packages that are not yet published to NPM. 
I test it on my local with latest master branch, seems still have the cutoff issue. However if I go to node_modules manually replacing the rCellHeight calculation in jspdf.plugin.autotable.js, it did fix the issue.
![image](https://user-images.githubusercontent.com/13965345/55883610-a55a4000-5b74-11e9-8cda-8baf6e924cc5.png)

**Comment by jackiewang5566** [comment]
Even if I pull master branch from npm, it's still using 3.1.1's jspdf.plugin.autotable.js which does not include the change, but if I manually update the rCellHeight calculation, it did fix the issue on my local, so I think the code from @rong4188 for updating rCellHeight in tableDrawer.ts is working. It's just not reflected in jspdf.plugin.autotable.js pulled from master branch. Thanks @simonbengtsson and @rong4188

**Comment by simonbengtsson** [comment]
Can't reproduce anymore. And the example doesn't seem to show the issue? Can you create a minimal example highlighting the issue instead? Without angular etc.

**Comment by jackiewang5566** [comment]
This issue has been resolved, thanks @rong4188  commit.
